[WIP] [Feature] Implement form reset
houseform/houseform pull request #70
Opened 2023-03-21 21:42 UTC by ShooTeX

closes #62

2023-03-21 22:00 UTC, crutchcorn requested changes
Looks great overall! Some minor notes

2023-03-21 22:02 UTC, ShooTeX commented on lib/form/form.spec.tsx
> +  );
will do!

2023-03-21 22:03 UTC, ShooTeX commented on lib/form/form.tsx
> +    _setErrors(null);
the initialValue of `_errors` is `null` and I don't see it set to `[]` or am I missing something?

2023-03-21 22:06 UTC, ShooTeX commented
there is still a weird side effect where field arrays will reset to an empty field after submitting multiple times, can't really tell why this is happening

https://user-images.githubusercontent.com/10850738/226752199-ec440f1b-661d-47c3-b4d2-98d8a071c340.mov

2023-03-24 03:50 UTC, crutchcorn commented
@ShooTeX this issue should be fixed now. I'll also fix the merge conflicts for ya :)

2023-03-24 21:54 UTC, merged

2023-03-26 03:01 UTC, crutchcorn commented
@all-contributors please add @caxco93 for code, test, doc

2023-03-26 03:03 UTC, crutchcorn commented
Oh whoops that's the wrong username 🤦

2023-03-26 03:03 UTC, crutchcorn commented
@all-contributors please add @ShooTeX for code, test, doc